all:
  hosts:
    server1:
      ansible_host: 192.168.1.101
      ansible_user: your_username
      ansible_ssh_pass: your_password
    server2:
      ansible_host: 192.168.1.102
      ansible_user: your_username
      ansible_ssh_pass: your_password
